apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: harbor.cicd.local:30002/library/demo-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "latest"
